development:
  adapter: postgresql
  encoding: unicode
  database: templates_development
  pool: 5
  username: postgres
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: templates_test
  pool: 5
  username: postgres
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: templates_production
  pool: 5
  username: postgres
  password:
