development:
  adapter: postgresql
  encoding: unicode
  database: socks_development
  pool: 16
  username: postgres
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: socks_test
  pool: 16
  username: postgres
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: socks_production
  pool: 16
  username: postgres
  password:
